require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'


target 'My_Qari' do
  config = use_native_modules!
  
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  permissions_path = '../node_modules/react-native-permissions/ios' # 혜림추가

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"

  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"

  use_react_native!(:path => config["reactNativePath"])

end

